### ISSUE TITLE
circleci: codecov error

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/core#1481]
**Describe the bug**

The logs show the following error:

```
Failed to collect coverage from /home/circleci/ark-core/packages/core-snapshots/lib/transport/index.js
ERROR: /home/circleci/ark-core/packages/core-snapshots/lib/transport/index.js: Unexpected token, expected ( (114:8)
STACK: SyntaxError: /home/circleci/ark-core/packages/core-snapshots/lib/transport/index.js: Unexpected token, expected ( (114:8)
  112 | 
  113 |     emitter.emit('start', { count: options.meta[table].count })
> 114 |     for await (const record of readStream) {
      |         ^
  115 |       counter++
  116 |       if (!verifyData(table, record, prevData, options.signatureVerification)) {
  117 |         container.forceExit(
    at Parser.pp$5.raise (/home/circleci/ark-core/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/circleci/ark-core/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/home/circleci/ark-core/node_modules/babylon/lib/index.js:1749:33)
    at Parser.pp$1.parseForStatement (/home/circleci/ark-core/node_modules/babylon/lib/index.js:2008:8)
    at Parser.pp$1.parseStatement (/home/circleci/ark-core/node_modules/babylon/lib/index.js:1836:19)
    at Parser.pp$1.parseBlockBody (/home/circleci/ark-core/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/home/circleci/ark-core/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/home/circleci/ark-core/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (/home/circleci/ark-core/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseAsyncArrowFromCallExpression (/home/circleci/ark-core/node_modules/babylon/lib/index.js:3590:15)
```

this error does however not cause a failure.

**To Reproduce**
Execute the tests in CircleCI

**Comment by faustbrian** [comment]
This issue will show up if anything lower then node 10 is used to run the code.

**Comment by dated** [comment]
Good to know, thanks!
