### ISSUE TITLE
circleci: disrupted connection

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/core#1482]
**Describe the bug**
i sometimes get the following error when running tests on CircleCI:

```
    This socket has been ended by the other party

      at Connection.Object.<anonymous>.Connection.end (node_modules/pg/lib/connection.js:319:22)
      at Client.Object.<anonymous>.Client.end (node_modules/pg/lib/client.js:453:21)
      at Pool._remove (node_modules/pg-pool/index.js:143:12)
      at Timeout.setTimeout (node_modules/pg-pool/index.js:46:12)
```

**Comment by faustbrian** [comment]
@air1one is already looking into it.
