### ISSUE TITLE
Timeout occurs when using json rpc (port related questions.)

### ISSUE THREAD

**Issue by leeheejoo** [ArkEcosystem/core#1912]
**I have a question. 
I keep getting a timeout when I send the json rpc (transactions.broadcast) command. 
I wonder if it is a firewall problem. 
I have only 4001 port(outbound) open.
RPC and JSON-RPC ports are not open. The test was tested with curl inside the server.**

$ curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:8080 
             -d '{
                "jsonrpc": "2.0",
                 "id": "unique-request-id",
                 "method": "transactions.bip38.create",
                 "params": { "userId": "b89eed78af919cd9b",
                     "bip38": "ceiling heavy episode rocket region dress decrease ghost bulk ability apology pill cry mountain horn",
                     "amount": 10000000,
                     "recipientId": "AbrFUJ6GdNvYRu9K9HRPc3uxcVjhRZbKjD"
                 }
             }' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1021  100   483  100   538    136    151  0:00:03  0:00:03 --:--:--   287
{
    "id": "unique-request-id",
    "jsonrpc": "2.0",
    "result": {
	    "amount": 10000000,
        "fee": 10000000,
        "id": "6fb80e7a56f7a7c2815b3cb938987a48f7257fcefac4509ba0eb8a4211f4fe58",
        "recipientId": "AbrFUJ6GdNvYRu9K9HRPc3uxcVjhRZbKjD",
        "senderPublicKey": "0261510b05e18df78ea1ee8fd8d06c74a816de0fe64507ab70904b5f242068f02a",
        "signature": "3045022100be17a9aa988033acad642320ef97617472ea657037368224c7879881545f64e102205a594dc5f455a3f83f5d8c1436cb1ec8a65ef36ad1526d1b9c2e516e4d9812c3",
		"timestamp": 55785984,
        "type": 0
    }
}

$ curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:8080 
             -d '{
                 "jsonrpc": "2.0",
                 "id": "unique-request-id",
                 "method": "transactions.broadcast",
                 "params": {
                     "id": "6fb80e7a56f7a7c2815b3cb938987a48f7257fcefac4509ba0eb8a4211f4fe58"
                 }
             }' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   797  100   514  100   283    170     93  0:00:03  0:00:03 --:--:--   264
{
    "error": {
        "code": -32603,
		"data": "Error: timeout of 3000ms exceeded\n    at createError (/home/ark/core/node_modules/axios/lib/core/createError.js:16:15)\n    at Timeout.handleRequestTimeout [as _onTimeout] (/home/ark/core/node_modules/axios/lib/adapters/http.js:216:16)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)",
        "message": "timeout of 3000ms exceeded"
    },
    "id": "unique-request-id",
    "jsonrpc": "2.0"
}

**Comment by faustbrian** [comment]
Transactions are broadcasted to the public API of other peers over port 4003.
