### ISSUE TITLE
Rollback issue: Cannot read property 'timestamp' of null

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/core#3180]
On one of my Devnet servers during rollback I got this error that I haven't seen in the past:

`[2019-10-30 09:44:47.804] DEBUG: ark-snapshot 2.6.0-next.3
[2019-10-30 09:44:47.812] DEBUG: Data Directory: /home/ark/.local/share/ark-core/devnet
[2019-10-30 09:44:47.813] DEBUG: Config Directory: /home/ark/.config/ark-core/devnet
[2019-10-30 09:44:47.814] DEBUG: Cache Directory: /home/ark/.cache/ark-core/devnet
[2019-10-30 09:44:47.815] DEBUG: Log Directory: /home/ark/.local/state/ark-core/devnet
[2019-10-30 09:44:47.816] DEBUG: Temp Directory: /tmp/ark/ark-core/devnet
[2019-10-30 09:44:48.190] INFO : Starting Database Manager
[2019-10-30 09:44:48.192] INFO : Establishing Database Connection
[2019-10-30 09:44:48.193] DEBUG: Connecting to database
[2019-10-30 09:44:48.389] DEBUG: Connected to database.
TypeError: Cannot read property 'timestamp' of null
    at SnapshotManager.rollbackByHeight (~/.config/yarn/global/node_modules/@arkecosystem/core-snapshots/dist/manager.js:83:101)
    at async RollbackCommand.run (~/.config/yarn/global/node_modules/@arkecosystem/core/dist/commands/snapshot/rollback.js:15:13)
    at async RollbackCommand._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
[2019-10-30 09:44:48.856] INFO : Core is trying to gracefully shut down to avoid data corruption
`

**Comment by vasild** [comment]
@boldninja at what height was your database when you executed the rollback and what was the exact rollback command?

**Comment by vasild** [comment]
```
ark=> select max(height) from blocks;
   max   
---------
 4022188
(1 row)

ark=> \q
ark@tester:~$ ark snapshot:rollback --height=4005000
[2019-10-30 14:14:35.422] DEBUG: ark-snapshot 2.6.0-next.3
[2019-10-30 14:14:35.429] DEBUG: Data Directory: /home/ark/.local/share/ark-core/devnet
[2019-10-30 14:14:35.430] DEBUG: Config Directory: /home/ark/.config/ark-core/devnet
[2019-10-30 14:14:35.431] DEBUG: Cache Directory: /home/ark/.cache/ark-core/devnet
[2019-10-30 14:14:35.432] DEBUG: Log Directory: /home/ark/.local/state/ark-core/devnet
[2019-10-30 14:14:35.433] DEBUG: Temp Directory: /tmp/ark/ark-core/devnet
[2019-10-30 14:14:35.810] INFO : Starting Database Manager
[2019-10-30 14:14:35.812] INFO : Establishing Database Connection
[2019-10-30 14:14:35.813] DEBUG: Connecting to database
[2019-10-30 14:14:35.956] DEBUG: Connected to database.
TypeError: Cannot read property 'timestamp' of null
    at SnapshotManager.rollbackByHeight (~/.config/yarn/global/node_modules/@arkecosystem/core-snapshots/dist/manager.js:83:101)
    at async RollbackCommand.run (~/.config/yarn/global/node_modules/@arkecosystem/core/dist/commands/snapshot/rollback.js:15:13)
    at async RollbackCommand._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
[2019-10-30 14:14:36.364] INFO : Core is trying to gracefully shut down to avoid data corruption
ark@tester:~$ 
```
