### ISSUE TITLE
multipleResolves when P2P requests time out and disconnect

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#4159]
```
19|ark-core  | [2020-11-11 01:53:53.232] DEBUG	: Socket error (peer 23.227.207.73) : Disconnecting due to heartbeat timeout
19|ark-core  | [2020-11-11 01:53:53.241] DEBUG	: Socket error (peer 23.227.207.73) : Disconnecting due to heartbeat timeout
19|ark-core  | [2020-11-11 01:53:56.897] DEBUG	: Socket error (peer 51.15.137.196) : Connection timed out
19|ark-core  | [2020-11-11 01:54:03.182] DEBUG	: Socket error (peer 51.15.137.196) : Connection timed out
19|ark-core  | [2020-11-11 01:54:10.599] DEBUG	: Socket error (peer 51.15.137.196) : Connection timed out
19|ark-core  |  ℹ  multipleResolves (a promise was rejected multiple times)
19|ark-core  | Initially rejected with: Error: Request timed out
19|ark-core  | Then rejected again with: Error: Request failed - server disconnected
19|ark-core  |     at NesError (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-p2p/dist/hapi-nes/client.js:39:15)
19|ark-core  |     at Client._cleanup (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-p2p/dist/hapi-nes/client.js:261:23)
19|ark-core  |     at WebSocket.reconnect (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-p2p/dist/hapi-nes/client.js:167:18)
19|ark-core  |     at WebSocket.onClose (/home/ark/.config/yarn/global/node_modules/ws/lib/event-target.js:129:16)
19|ark-core  |     at WebSocket.emit (events.js:314:20)
19|ark-core  |     at WebSocket.emitClose (/home/ark/.config/yarn/global/node_modules/ws/lib/websocket.js:191:10)
19|ark-core  |     at Socket.socketOnClose (/home/ark/.config/yarn/global/node_modules/ws/lib/websocket.js:858:15)
19|ark-core  |     at Socket.emit (events.js:314:20)
19|ark-core  |     at TCP.<anonymous> (net.js:676:12)
19|ark-core  | [2020-11-11 01:54:25.497] DEBUG	: Socket error (peer 51.15.137.196) : Connection timed out
19|ark-core  | [2020-11-11 01:54:29.236] DEBUG	: Socket error (peer 23.227.207.73) : Socket error
19|ark-core  | [2020-11-11 01:54:29.237] DEBUG	: Socket error (peer 23.227.207.73) : Connection timed out
19|ark-core  | [2020-11-11 01:54:29.243] DEBUG	: Socket error (peer 23.227.207.73) : Socket error
19|ark-core  | [2020-11-11 01:54:29.244] DEBUG	: Socket error (peer 23.227.207.73) : Connection timed out
19|ark-core  | [2020-11-11 01:54:31.730] DEBUG	: Socket error (peer 51.15.137.196) : Connection timed out
```

**Comment by rainydio** [comment]
It appears that @sebastijankuzner already [fixed it]

[fixed it]: https://github.com/ArkEcosystem/core/commit/76aebaed3901088b11e60d3e5c3925ef35def19d#diff-eeafe37f7325180edff18317ffd8f54b967c1df943529e839abf17e618d286abR432
