### ISSUE TITLE
QueryFailedError on process restart (v3)

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/core#4164]
```
2|ark-forger  | QueryFailedError: deadlock detected
2|ark-forger  |     at new QueryFailedError (/home/ark_devnet/.config/yarn/global/node_modules/typeorm/error/QueryFailedError.js:11:28)
2|ark-forger  |     at Query.callback (/home/ark_devnet/.config/yarn/global/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
2|ark-forger  |     at Query.handleError (/home/ark_devnet/.config/yarn/global/node_modules/pg/lib/query.js:128:19)
2|ark-forger  |     at Client._handleErrorMessage (/home/ark_devnet/.config/yarn/global/node_modules/pg/lib/client.js:326:17)
2|ark-forger  |     at Connection.emit (events.js:314:20)
2|ark-forger  |     at /home/ark_devnet/.config/yarn/global/node_modules/pg/lib/connection.js:109:12
2|ark-forger  |     at Parser.parse (/home/ark_devnet/.config/yarn/global/node_modules/pg-protocol/dist/parser.js:40:17)
2|ark-forger  |     at Socket.<anonymous> (/home/ark_devnet/.config/yarn/global/node_modules/pg-protocol/dist/index.js:10:42)
2|ark-forger  |     at Socket.emit (events.js:314:20)
2|ark-forger  |     at addChunk (_stream_readable.js:298:12)
2|ark-forger  | [ERROR] [@arkecosystem/core-database] Failed to register: "deadlock detected".
PM2           | App [ark-forger:2] exited with code [1] via signal [SIGINT]
PM2           | App [ark-forger:2] starting in -fork mode-
PM2           | App [ark-forger:2] online
```

Alternative version:

```
QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
    at new QueryFailedError (/home/ark_devnet/.config/yarn/global/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/ark_devnet/.config/yarn/global/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/home/ark_devnet/.config/yarn/global/node_modules/pg/lib/query.js:128:19)
    at Client._handleErrorMessage (/home/ark_devnet/.config/yarn/global/node_modules/pg/lib/client.js:326:17)
    at Connection.emit (events.js:314:20)
    at /home/ark_devnet/.config/yarn/global/node_modules/pg/lib/connection.js:109:12
    at Parser.parse (/home/ark_devnet/.config/yarn/global/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/ark_devnet/.config/yarn/global/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
[ERROR] [@arkecosystem/core-database] Failed to register: "duplicate key value violates unique constraint "pg_type_typname_nsp_index"".
```

A quick google search suggests they both seem to be caused by the same thing, namely a concurrency issue/race condition when the individual forger and relay processes restart (and thus reconnect to the database) at the same time.

**Comment by alessiodf** [comment]
An observation is that the `duplicate key value violates unique constraint "pg_type_typname_nsp_index"` error is raised by the relay and `QueryFailedError: deadlock detected` is raised by the forger. So it seems that the error you get depends on which process loses the race.

**Comment by faustbrian** [comment]
https://app.clickup.com/t/a6xu2a
