### ISSUE TITLE
ℹ  multipleResolves (a promise was rejected multiple times)

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/core#4616]
During situations where a node has forked and continually tries (and fails) to download blocks from all other peers, Core will sometimes encounter a `multipleResolves` error similar to the following:

```
[2022-02-18 21:43:49.550] INFO: Failed to download blocks [544,492, 544,492] from 20.94.228.251:4000: Peer did not return any block
[2022-02-18 21:43:49.551] DEBUG: Throttling outgoing requests to 23.94.103.199/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:49.602] DEBUG: Peer 144.91.90.203 did not return any blocks via height 544,493.
[2022-02-18 21:43:49.603] INFO: Failed to download blocks [544,494, 544,494] from 144.91.90.203:4000: Peer did not return any block
[2022-02-18 21:43:49.604] DEBUG: Throttling outgoing requests to 23.94.103.199/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:49.649] DEBUG: Throttling outgoing requests to 144.91.90.203/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:49.733] DEBUG: Throttling outgoing requests to 23.94.56.224/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:49.822] INFO: 144.91.90.203 has downloaded 400 blocks from height 532,998
[2022-02-18 21:43:49.843] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:49.866] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.494] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.511] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.524] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.551] DEBUG: Throttling outgoing requests to 23.94.103.199/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.650] DEBUG: Throttling outgoing requests to 144.91.90.203/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.737] DEBUG: Peer 23.94.103.199 did not return any blocks via height 544,493.
[2022-02-18 21:43:50.738] INFO: Failed to download blocks [544,494, 544,494] from 23.94.103.199:4000: Peer did not return any block
[2022-02-18 21:43:50.739] DEBUG: Throttling outgoing requests to 23.94.56.224/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.845] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.866] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.878] DEBUG: Peer 23.94.56.224 did not return any blocks via height 544,490.
[2022-02-18 21:43:50.878] INFO: Failed to download blocks [544,491, 544,491] from 23.94.56.224:4000: Peer did not return any block
[2022-02-18 21:43:50.982] DEBUG: Peer 23.95.146.118 did not return any blocks via height 544,490.
[2022-02-18 21:43:50.983] INFO: Failed to download blocks [544,491, 544,491] from 23.95.146.118:4000: Peer did not return any block
[2022-02-18 21:43:50.983] ERROR: Could not download blocks [544,491, 544,491] from any of 6 peer(s). Last attempt returned 0 block(s) from peer 23.95.146.118:4000.
[2022-02-18 21:43:50.984] INFO: Could not download any blocks from any peer from height 544,491
[2022-02-18 21:43:50.985] DEBUG: event 'NOBLOCK': {"syncWithNetwork":"downloadBlocks"} -> {"syncWithNetwork":"syncing"} -> actions: [checkLastDownloadedBlockSynced]
[2022-02-18 21:43:50.986] DEBUG: Queued chunks of blocks (process: 0)
[2022-02-18 21:43:50.987] DEBUG: event 'NOTSYNCED': {"syncWithNetwork":"syncing"} -> {"syncWithNetwork":"downloadBlocks"} -> actions: [downloadBlocks]
[2022-02-18 21:43:50.988] DEBUG: Downloading blocks in chunks: [544,491, 544,491], [544,492, 544,492], [544,493, 544,493], [544,494, 544,494], [544,495, ..]
[2022-02-18 21:43:50.989] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.990] DEBUG: Throttling outgoing requests to 144.91.90.203/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.990] DEBUG: Throttling outgoing requests to 23.94.103.199/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:50.991] DEBUG: Throttling outgoing requests to 23.95.146.118/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:51.014] DEBUG: Peer 116.203.121.209 did not return any blocks via height 544,490.
[2022-02-18 21:43:51.015] INFO: Failed to download blocks [544,491, 544,491] from 116.203.121.209:4000: Peer did not return any block
[2022-02-18 21:43:51.015] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:51.513] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:51.526] DEBUG: Throttling outgoing requests to 20.94.228.251/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:51.552] DEBUG: Throttling outgoing requests to 23.94.103.199/p2p.blocks.getBlocks to avoid triggering their rate limit
[2022-02-18 21:43:51.650] DEBUG: Peer 20.94.228.251 did not return any blocks via height 544,492.
[2022-02-18 21:43:51.651] INFO: Failed to download blocks [544,493, 544,493] from 20.94.228.251:4000: Peer did not return any block
[2022-02-18 21:43:51.652] INFO: Giving up on trying to download blocks [544,493, 544,493]: another download job failed

 ℹ  multipleResolves (a promise was rejected multiple times) 
Initially rejected with: Error: Could not download blocks [544,492, 544,492] from any of 6 peer(s). Last attempt returned 0 block(s) from peer 20.94.228.251:4000.
Then rejected again with: Error: Could not download blocks [544,493, 544,493] from any of 6 peer(s). Last attempt returned 0 block(s) from peer 20.94.228.251:4000.
    at /home/ark/core/packages/core-p2p/dist/network-monitor.js:305:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 2)
```

**Comment by sebastijankuzner** [comment]
This is caused by [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#description) method, when more than one Promise is rejected on this [line](https://github.com/ArkEcosystem/core/blob/b17ad4ccfb86c40efb9aa41bac7dd31e5e3c403b/packages/core-p2p/src/network-monitor.ts#L443). 

Multiple resolves are printed when such event happens. It indicates that more than one chunk was not downloaded.

**Comment by alessiodf** [comment]
Maybe `multipleResolves` errors should be suppressed in that case? They've been deprecated in later versions of Node.js due to their unreliability: https://nodejs.org/api/process.html#event-multipleresolves

In fact, the latest version of `log-process-errors` (which Core uses for this type of logging) removes `multipleResolves` support entirely for this reason.

At the moment the logging of this makes it seem like a Core bug even when it isn't (especially since it says "Error" with a stack trace)...
