### ISSUE TITLE
core-deployer test fails, bad require

### ISSUE THREAD

**Issue by JeremiGendron** [ArkEcosystem/core#700]
**Describe the bug**
currently, tests for core-deployer/builder requires a file for that is no longer there

**To Reproduce**
1. Go to '$/packages/core-deployer'
2. Type 'yarn test' + enter
3. Wait a bit and read logs
`
yarn run v1.7.0
$ ARK_ENV=test jest --forceExit
 FAIL  __tests__/builder/genesis-block.test.js
  ● Test suite failed to run

    Cannot find module '../../../crypto/lib/config/testnet/network' from 'genesis-block.test.js'

      2 | 
      3 | const GenesisBlockBuilder = require('../../lib/builder/genesis-block')
    > 4 | const network = require('../../../crypto/lib/config/testnet/network')
      5 | 
      6 | let builder
      7 | let genesis
      
      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (__tests__/builder/genesis-block.test.js:4:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.749s
Ran all test suites.
`

**Expected behavior**
requires a package/file that exists and uses its data appropriately within the test

**Server**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
opening PR

**Comment by JeremiGendron** [comment]
oops, fixed in another PR from @j-a-m-l
